//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppReports
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppReports()
        {
            this.CloseAction = false;
        }
    
        public int ID { get; set; }
        public string UserName { get; set; }
        public string PcName { get; set; }
        public string Message { get; set; }
        public byte[] FileData { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> AddTime { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
        public string Reply { get; set; }
        public Nullable<bool> CloseAction { get; set; }
    }
}
