//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosRanks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PosRanks()
        {
            this.Attachments = new HashSet<Attachments>();
        }
    
        public int ID { get; set; }
        public int Rank { get; set; }
        public Nullable<System.DateTime> DateAdd { get; set; }
        public string Description { get; set; }
        public Nullable<int> Pos_ID { get; set; }
        public Nullable<bool> ActiveRank { get; set; }
    
        public virtual Pos Pos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachments> Attachments { get; set; }
    }
}
