//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleDetails
    {
        public int ID { get; set; }
        public System.DateTime dateAdd { get; set; }
        public Nullable<int> Status_ID { get; set; }
        public Nullable<int> Sample_ID { get; set; }
    
        public virtual SampleDetailStatus SampleDetailStatus { get; set; }
        public virtual Samples Samples { get; set; }
    }
}
