//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleAttachments
    {
        public int SampleAttachmentID { get; set; }
        public Nullable<int> SampleID { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public byte[] FileData { get; set; }
    
        public virtual Samples Samples { get; set; }
    }
}
