//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samples
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samples()
        {
            this.SampleDetails = new HashSet<SampleDetails>();
            this.SampleAttachments = new HashSet<SampleAttachments>();
        }
    
        public int ID { get; set; }
        public int sampleStatus { get; set; }
        public Nullable<System.DateTime> dateAdd { get; set; }
        public Nullable<System.DateTime> dateRequestForApproval { get; set; }
        public Nullable<System.DateTime> dateApproval { get; set; }
        public Nullable<System.DateTime> dateOrder { get; set; }
        public Nullable<System.DateTime> dateShip { get; set; }
        public Nullable<System.DateTime> dateInstallation { get; set; }
        public Nullable<int> Pos_ID { get; set; }
    
        public virtual Pos Pos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleDetails> SampleDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleAttachments> SampleAttachments { get; set; }
    }
}
