//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID { get; set; }
        public string login { get; set; }
        public bool DealerOwner { get; set; }
        public Nullable<int> dealer_ID { get; set; }
        public Nullable<int> userRole_ID { get; set; }
    
        public virtual Dealers Dealers { get; set; }
        public virtual UserRoles UserRoles { get; set; }
    }
}
